### ISSUE TITLE
Option no not reset variables set in the initialization script

### ISSUE THREAD

**Issue by Fideruchan** [idaocracy/NaninovelSceneAssistant#1]
Hello,

thanks for this great tool. I have a suggestion if you think is useful. In my projects I normally have a lots of variables that are set in the initiazilation script instead of the Naninovel settings. In the assistant, each time you "switch" to another script, it reset all the variables, even the ones set in the initialisation script. Is it possible to stay with that variables every time a new script is loaded thru the interface?

Thank you very much!

**Comment by idaocracy** [comment]
If by reset you mean the field becomes empty on reset? That appears to only affect local variables and not global variables and the problem also occurs when using the built-in var debug menu, meaning it's an issue on Naninovel's side. I'll forward this to Elringus.

**Comment by idaocracy** [comment]
My bad, it was actually an issue on my side and the issue should be fixed. Make sure the vars you initialize via init script are global only as local variables are only initialized in case the game doesn't have a title screen.

**Comment by Fideruchan** [comment]
Yes, I thought that was the case, but I have global and local variables in the init script and they persists after the tittle screen and a press "new game". I did this because I have a lot of variables and put them in the custom variables window is pain :-( I'll make a few more test for this. Thank you! :-)
