### ISSUE TITLE
error CS1061: 'TUI' does not contain a definition for 'ModalGroup' and...

### ISSUE THREAD

**Issue by katrinshtorm** [idaocracy/NaninovelSceneAssistant#2]
I've set it according to instruction, but it gives me this red error

Library\PackageCache\com.idaocracy.naninovelsceneassistant@43884b42e3\Runtime\ObjectData\Values\UIData.cs(36,29): error CS1061: 'TUI' does not contain a definition for 'ModalGroup' and no accessible extension method 'ModalGroup' accepting a first argument of type 'TUI' could be found (are you missing a using directive or an assembly reference?)
![photo_2024-06-11_14-14-39](https://github.com/idaocracy/NaninovelSceneAssistant/assets/77185151/9df7a612-eb0e-4eb9-acec-74f7a8bd4b68)

**Comment by idaocracy** [comment]
The ModalGroup feature was introduced in a pre-release version of 1.19, so you're likely using an older version of Naninovel. The extension is designed to be used with the stable version of Naninovel 1.19, which is available through Naninovel's Discord channel. 

https://naninovel.com/support/
