### ISSUE TITLE
Compilation errors for Naninovel 1.20.20240720

### ISSUE THREAD

**Issue by Gamer-XP** [idaocracy/NaninovelSceneAssistant#3]
Because of CustomVariable changes, assistant does not compile anymore

**Comment by idaocracy** [comment]
Fixed. The current workaround is very hacky so if you run into more problems, let me know.

**Comment by Gamer-XP** [comment]
I still get some compilation errors
https://gyazo.com/c1de51e70044935c1db83fde83849752
Checked the commit, and it didn't change this file.

**Comment by idaocracy** [comment]
Should be fixed now.

**Comment by Gamer-XP** [comment]
Maybe something to do with Unity version. I'm using Unity 6. I guess need to explicitly say which to use.
https://gyazo.com/a715c5094fe1819d86e1257f270d3683

**Comment by idaocracy** [comment]
Could be (I stick to the recommended versions such as 2022.3 for 1.20). I updated the references, any luck now?

**Comment by Gamer-XP** [comment]
Yep, works now. Thanks!
